[env]
_.python.venv = { path = ".venv", create = true }

[tools]
python = "3.14"
uv = "latest"
"npm:pyright" = "latest"
"npm:backlog.md" = "latest"

[settings]
disable_backends = ["pipx"]
pipx.uvx = true
