package cli

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/brettinternet/worklease/internal/reason"
)

func TestCompletionScriptsAreSupportedDeterministicAndReadOnly(t *testing.T) {
	home := t.TempDir() + "/never-created"
	markers := map[string]string{
		"bash": "complete -o bashdefault -o default -F __worklease_bash_autocomplete worklease",
		"zsh":  "compdef _worklease worklease",
		"fish": "complete -c worklease",
	}
	for shell, marker := range markers {
		t.Run(shell, func(t *testing.T) {
			render := func() string {
				var stdout, stderr bytes.Buffer
				args := []string{"worklease", "--home", home, "completion", shell}
				if err := Run(context.Background(), args, "dev", "unknown", "unknown", &stdout, &stderr); err != nil {
					t.Fatal(err)
				}
				if stderr.Len() != 0 {
					t.Fatalf("stderr=%q", stderr.String())
				}
				return stdout.String()
			}
			first := render()
			if first != render() {
				t.Fatal("completion script is not deterministic")
			}
			if !strings.Contains(first, marker) {
				t.Fatalf("completion script lacks %q", marker)
			}
			if strings.Contains(first, "\x1b") {
				t.Fatal("completion script contains ANSI sequences")
			}
			if shell == "bash" {
				if !strings.Contains(first, "elif declare -F _get_comp_words_by_ref") || !strings.Contains(first, `cur="${COMP_WORDS[COMP_CWORD]}"`) {
					t.Fatal("Bash completion lacks its dependency-free fallback")
				}
				if strings.Contains(first, "eval") || !strings.Contains(first, `opts=$("${__worklease_completion_request[@]}"`) {
					t.Fatal("Bash completion does not preserve request arguments safely")
				}
			}
		})
	}
	if _, err := os.Stat(home); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("completion generation touched the authority home: %v", err)
	}
}

func TestBashCompletionWorksWithoutBashCompletionAndDoesNotEvaluateArguments(t *testing.T) {
	var generated bytes.Buffer
	if err := Run(context.Background(), []string{"worklease", "completion", "bash"}, "dev", "unknown", "unknown", &generated, &bytes.Buffer{}); err != nil {
		t.Fatal(err)
	}
	directory := t.TempDir()
	sentinel := filepath.Join(directory, "command-substitution-ran")
	fake := filepath.Join(directory, "worklease")
	if err := os.WriteFile(fake, []byte("#!/bin/sh\nprintf '%s\\n' 'version:print the version'\n"), 0o755); err != nil {
		t.Fatal(err)
	}
	script := generated.String() + "\nunset -f _comp_initialize _get_comp_words_by_ref\n" +
		"COMP_WORDS=(worklease '$(touch " + sentinel + ")' '')\n" +
		"COMP_CWORD=2\n__worklease_bash_autocomplete\nprintf '%s\\n' \"${COMPREPLY[@]}\"\n"
	scriptPath := filepath.Join(directory, "completion-smoke.bash")
	if err := os.WriteFile(scriptPath, []byte(script), 0o600); err != nil {
		t.Fatal(err)
	}
	command := exec.Command("bash", "--noprofile", "--norc", scriptPath)
	command.Env = append(os.Environ(), "PATH="+directory+":"+os.Getenv("PATH"))
	output, err := command.CombinedOutput()
	if err != nil {
		t.Fatalf("clean Bash completion failed: %v: %s", err, output)
	}
	if !strings.Contains(string(output), "version") {
		t.Fatalf("clean Bash returned no completion: %q", output)
	}
	if _, err := os.Stat(sentinel); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("completion evaluated a command substitution: %v", err)
	}
}

func TestCompletionSuggestionsCoverTreeAliasesAndOptionsForEveryShell(t *testing.T) {
	home := t.TempDir() + "/never-created"
	tests := []struct {
		name string
		args []string
		want []string
		not  []string
	}{
		{name: "root", args: []string{"worklease", "--generate-shell-completion"}, want: []string{"list:list current claims", "ls:list current claims", "completion:generate shell completion", "op:inspect or reconcile operations", "help:show help", "h:show help"}, not: []string{"--generate-shell-completion"}},
		{name: "nested", args: []string{"worklease", "op", "--generate-shell-completion"}, want: []string{"inspect:inspect an operation", "reconcile:reconcile an operation"}},
		{name: "policy list alias", args: []string{"worklease", "policy", "--generate-shell-completion"}, want: []string{"list:list built-in policies", "ls:list built-in policies"}},
		{name: "profile list alias", args: []string{"worklease", "profile", "--generate-shell-completion"}, want: []string{"list:list trusted remote authority profiles", "ls:list trusted remote authority profiles"}},
		{name: "installation list alias", args: []string{"worklease", "installation", "--generate-shell-completion"}, want: []string{"list:list remote installations", "ls:list remote installations"}},
		{name: "alias", args: []string{"worklease", "ev", "--generate-shell-completion"}, want: []string{"events:show lifecycle events", "event:show lifecycle events"}},
		{name: "global option", args: []string{"worklease", "--h", "--generate-shell-completion"}, want: []string{"--home:state directory", "-H:state directory", "--help:show help"}, not: []string{"--generate-shell-completion"}},
		{name: "local option", args: []string{"worklease", "acquire", "--po", "--generate-shell-completion"}, want: []string{"--poll-interval:DURATION between contention polls", "--wait:wait up to DURATION", "-w:wait up to DURATION", "--home:state directory"}},
	}
	for _, shell := range []string{"bash", "zsh", "fish"} {
		t.Run(shell, func(t *testing.T) {
			for _, test := range tests {
				t.Run(test.name, func(t *testing.T) {
					var stdout, stderr bytes.Buffer
					args := append([]string{"worklease", "--home", home}, test.args[1:]...)
					if err := Run(context.Background(), args, "dev", "unknown", "unknown", &stdout, &stderr); err != nil {
						t.Fatal(err)
					}
					if stderr.Len() != 0 {
						t.Fatalf("stderr=%q", stderr.String())
					}
					for _, want := range test.want {
						if !strings.Contains(stdout.String(), want) {
							t.Errorf("completion output lacks %q: %q", want, stdout.String())
						}
					}
					for _, unwanted := range test.not {
						if strings.Contains(stdout.String(), unwanted) {
							t.Errorf("completion output contains hidden plumbing %q", unwanted)
						}
					}
				})
			}
		})
	}
	if _, err := os.Stat(home); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("completion requests touched the authority home: %v", err)
	}
}

func TestCompletionMarkerAfterSeparatorNeverDispatchesCommand(t *testing.T) {
	var stdout, stderr bytes.Buffer
	args := []string{"worklease", "version", "--", "ignored-child-argument", "--generate-shell-completion"}
	if err := Run(context.Background(), args, "must-not-be-printed", "unknown", "unknown", &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	if stdout.Len() != 0 || stderr.Len() != 0 {
		t.Fatalf("completion dispatched the command: stdout=%q stderr=%q", stdout.String(), stderr.String())
	}
	got := safeCompletionArgs(args)
	want := []string{"worklease", "version", "--generate-shell-completion"}
	if strings.Join(got, "\x00") != strings.Join(want, "\x00") {
		t.Fatalf("safe args=%v want=%v", got, want)
	}
	nonterminal := []string{"worklease", "exec", "--", "echo", "--generate-shell-completion", "literal"}
	if got := safeCompletionArgs(nonterminal); strings.Join(got, "\x00") != strings.Join(nonterminal, "\x00") {
		t.Fatalf("nonterminal marker changed: %v", got)
	}

	home := filepath.Join(t.TempDir(), "authority")
	session := "completion-no-dispatch"
	stdout.Reset()
	if err := Run(context.Background(), []string{"worklease", "--local", "--home", home, "acquire", "--resource", "completion-test", "--session", session}, "dev", "unknown", "unknown", &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	revision := func() float64 {
		t.Helper()
		stdout.Reset()
		if err := Run(context.Background(), []string{"worklease", "--local", "--home", home, "--json", "status", "--session", session}, "dev", "unknown", "unknown", &stdout, &stderr); err != nil {
			t.Fatal(err)
		}
		var status map[string]any
		if err := json.Unmarshal(stdout.Bytes(), &status); err != nil {
			t.Fatal(err)
		}
		claim, ok := status["claim"].(map[string]any)
		if !ok {
			t.Fatalf("status has no claim: %#v", status)
		}
		value, ok := claim["revision"].(float64)
		if !ok {
			t.Fatalf("claim has no numeric revision: %#v", claim)
		}
		return value
	}
	before := revision()
	sentinel := filepath.Join(t.TempDir(), "child-ran")
	stdout.Reset()
	if err := Run(context.Background(), []string{"worklease", "--local", "--home", home, "exec", "--session", session, "--", "sh", "-c", "printf ran > \"$1\"", "sh", sentinel, "--generate-shell-completion"}, "dev", "unknown", "unknown", &stdout, &stderr); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(sentinel); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("completion dispatched the guarded child: %v", err)
	}
	if after := revision(); after != before {
		t.Fatalf("completion mutated claim revision: before=%v after=%v", before, after)
	}
}

func TestCompletionRejectsUnsupportedShellClearly(t *testing.T) {
	var stdout, stderr bytes.Buffer
	err := Run(context.Background(), []string{"worklease", "completion", "powershell"}, "dev", "unknown", "unknown", &stdout, &stderr)
	if err == nil {
		t.Fatal("expected unsupported shell error")
	}
	if classified := reason.As(err); classified == nil || classified.Reason != reason.ReasonInvalidArgument {
		t.Fatalf("error=%v", err)
	}
	if !strings.Contains(err.Error(), `unsupported shell "powershell"; supported shells: bash, zsh, fish`) {
		t.Fatalf("error=%q", err)
	}
}
